version: '3'
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: grpc_cloudevents_zookeeper
    ports:
      - '2181:2181'
    environment:
      - 'ALLOW_ANONYMOUS_LOGIN=yes'
  kafka:
    image: 'wurstmeister/kafka:latest'
    container_name: grpc_cloudevents_kafka
    ports:
      - '9092:9092'
    environment:
      - 'KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181'
      - 'KAFKA_ADVERTISED_LISTENERS=INSIDE://kafka:29092,OUTSIDE://localhost:9092'
      - 'KAFKA_LISTENERS=INSIDE://:29092,OUTSIDE://:9092'
      - 'KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT'
      - 'KAFKA_INTER_BROKER_LISTENER_NAME=INSIDE'
      - 'ALLOW_PLAINTEXT_LISTENER=yes'
    depends_on:
      - zookeeper